[project]
name = "ortools-guide"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ortools>=9.11.4210",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
